name: Pull Request

on:

  pull_request:
    branches:
      - main

jobs:

  automerge_dependabot:
    uses: "philipcristiano/workflows/.github/workflows/automerge_dependabot.yml@main"
    with:
      automerge: true
    secrets:
      WF_GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v2.0.1

  docker_build:
    uses: "philipcristiano/workflows/.github/workflows/docker-build.yml@main"
    with:
      timeout: 25

  rust:
    uses: "philipcristiano/workflows/.github/workflows/rust.yml@main"

  flake:
    uses: "philipcristiano/workflows/.github/workflows/nix.yml@main"
    with:
      script: |
        cargo build
